#!/usr/bin/env python3
"""
استخراج cookies من المتصفح لـ Twitter/X
"""
import browser_cookie3
import sys

def extract_cookies():
    try:
        print("🔍 جاري استخراج cookies من Edge...")
        
        # محاولة Edge أولاً
        try:
            cookies = browser_cookie3.edge(domain_name='twitter.com')
            cookie_list = list(cookies)
            if cookie_list:
                print(f"✅ تم العثور على {len(cookie_list)} cookie من Edge")
                save_cookies(cookie_list, 'cookies.txt')
                return True
        except Exception as e:
            print(f"⚠️ فشل Edge: {e}")
        
        # محاولة Chrome
        try:
            cookies = browser_cookie3.chrome(domain_name='twitter.com')
            cookie_list = list(cookies)
            if cookie_list:
                print(f"✅ تم العثور على {len(cookie_list)} cookie من Chrome")
                save_cookies(cookie_list, 'cookies.txt')
                return True
        except Exception as e:
            print(f"⚠️ فشل Chrome: {e}")
        
        # محاولة Firefox
        try:
            cookies = browser_cookie3.firefox(domain_name='twitter.com')
            cookie_list = list(cookies)
            if cookie_list:
                print(f"✅ تم العثور على {len(cookie_list)} cookie من Firefox")
                save_cookies(cookie_list, 'cookies.txt')
                return True
        except Exception as e:
            print(f"⚠️ فشل Firefox: {e}")
        
        print("❌ لم يتم العثور على cookies في أي متصفح")
        print("💡 تأكد من تسجيل الدخول في Twitter/X في متصفحك")
        return False
        
    except Exception as e:
        print(f"❌ خطأ: {e}")
        return False

def save_cookies(cookies, filename):
    """حفظ الـ cookies بصيغة Netscape"""
    with open(filename, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by extract_cookies.py\n")
        f.write("# Edit at your own risk.\n\n")
        
        for cookie in cookies:
            domain = cookie.domain
            flag = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = cookie.path
            secure = 'TRUE' if cookie.secure else 'FALSE'
            expiration = str(int(cookie.expires)) if cookie.expires else '0'
            name = cookie.name
            value = cookie.value
            
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")
    
    print(f"💾 تم حفظ الملف: {filename}")

if __name__ == '__main__':
    success = extract_cookies()
    sys.exit(0 if success else 1)
