#!/usr/bin/env python3
"""
استخراج cookies من Edge/Chrome باستخدام pycookiecheat
"""
import sys
import os

def extract_from_edge():
    try:
        from pycookiecheat import chrome_cookies
        
        print("🔍 جاري استخراج cookies من Edge...")
        
        # مسار Edge cookies
        cookie_file = os.path.expanduser(
            r'~\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies'
        )
        
        if not os.path.exists(cookie_file):
            print(f"❌ ملف cookies غير موجود: {cookie_file}")
            return None
        
        # استخراج cookies لـ twitter.com
        cookies = chrome_cookies('https://twitter.com', cookie_file=cookie_file)
        
        if cookies:
            print(f"✅ تم العثور على {len(cookies)} cookie من Edge")
            return cookies
        else:
            print("⚠️ لم يتم العثور على cookies لـ Twitter/X")
            return None
            
    except Exception as e:
        print(f"❌ خطأ في Edge: {e}")
        return None

def save_cookies_netscape(cookies, filename='cookies.txt'):
    """حفظ الـ cookies بصيغة Netscape"""
    try:
        with open(filename, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was generated by extract_cookies_v2.py\n\n")
            
            for name, value in cookies.items():
                # صيغة Netscape: domain, flag, path, secure, expiration, name, value
                f.write(f".twitter.com\tTRUE\t/\tTRUE\t2147483647\t{name}\t{value}\n")
                f.write(f".x.com\tTRUE\t/\tTRUE\t2147483647\t{name}\t{value}\n")
        
        print(f"💾 تم حفظ {len(cookies)} cookie في: {filename}")
        return True
    except Exception as e:
        print(f"❌ فشل الحفظ: {e}")
        return False

def main():
    cookies = extract_from_edge()
    
    if cookies:
        if save_cookies_netscape(cookies):
            print("✅ تم بنجاح!")
            return 0
    
    print("\n💡 إذا لم ينجح، جرب:")
    print("1. تأكد من تسجيل الدخول في Twitter/X في Edge")
    print("2. أغلق Edge تماماً")
    print("3. شغل السكريبت مرة أخرى")
    
    return 1

if __name__ == '__main__':
    sys.exit(main())
